import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { TwemojiProvider } from "~/components/providers/twemoji";
import { Navbar } from "~/components/ui/navbar";
import Script from "next/script";
import { Monitoring } from "react-scan/monitoring/next"; // Import this first before React
import Footer from "~/components/ui/footer";

export const metadata: Metadata = {
  title: "tmw.gg",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={geist.variable}>
      <head>
        <Script
          src="https://unpkg.com/react-scan/dist/install-hook.global.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className="bg-white">
      <Monitoring
          apiKey="mMKMOnRHU6pIVkJ4CrhKFPg1HfB6lH8a" // Safe to expose publically
          url="https://monitoring.react-scan.com/api/v1/ingest"
          // commit={process.env.GIT_COMMIT_HASH} // optional but recommended
          // branch={process.env.GIT_BRANCH} // optional but recommended
        />
        <TwemojiProvider className="min-h-screen">
          <Navbar />
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </TwemojiProvider>
      </body>
    </html>
  );
}
